# Generated by Django 6.0.1 on 2026-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='scrapeddata',
            name='url',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='author',
            field=models.CharField(default='Anonimo', max_length=100),
            preserve_default=False,
        ),
    ]
