# Generated by Django 6.0.1 on 2026-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_title_scrapeddata_text_remove_scrapeddata_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='text',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='quote',
            field=models.TextField(default='Anonimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
